---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: cleaner
  namespace: gitlab-ci-kubernetes-namespace-cleaner

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-ci-kubernetes-namespace-cleaner
rules:
  - apiGroups: ['']
    resources: [namespaces]
    verbs: [delete, list]
  - apiGroups: ['']
    resources: [pods]
    verbs: [list]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-ci-kubernetes-namespace-cleaner
roleRef:
  kind: ClusterRole
  name: gitlab-ci-kubernetes-namespace-cleaner
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: cleaner
    namespace: gitlab-ci-kubernetes-namespace-cleaner
